version: "3.8"

services:
   web:
      build: .
      command: uvicorn traceapi.main:app --host 0.0.0.0 --port 8000 --reload
      volumes:
         - .:/traceapi
      ports:
         - "8000:8000"
      depends_on:
         - db
      environment:
         - DATABASE_URL=postgresql://user:password@db/mydatabase

   db:
      image: postgres:15
      volumes:
         - postgres_data:/var/lib/postgresql/data/
      environment:
         - POSTGRES_USER=user
         - POSTGRES_PASSWORD=password
         - POSTGRES_DB=mydatabase

volumes:
   postgres_data:
